# Generated by Django 3.0.2 on 2020-01-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='celular',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
