# Generated by Django 3.0.2 on 2020-01-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_pet_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('data_de_nascimento', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('cep', models.CharField(max_length=9)),
                ('numero', models.IntegerField()),
                ('celular', models.CharField(max_length=14)),
                ('motivo', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='pet',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='email',
        ),
    ]
